# StellariaCore 設定ファイル

server:
  prefix: "&%b[Stellaria] &r" # メッセージのPrefix !NOTE: 未実装
  name: "Stellaria"

economy:
  default-balance: 1000 # 新規プレイヤーの初期所持金
  balance-top-page-size: 10

scoreboard:
  title: "&%b&lSTELLARIA"
  update-interval-ticks: 20
  hide-numbers: true
  lines:
    - "&%7%server%"
    - "&%7オンライン: &%f%online%/%max_online%"
    - "&%7Ping: &%f%ping%ms"
    - "&%7ワールド: &%f%world%"
    - "&%7座標: &%f%x%, %y%, %z%"
    - "&%7所持金: &%e%money%"

tablist:
  header: "\n&%d%player%さん\n&%5すてらりあへようこそ\n"
  footer: "\n&%5stellaria.craftcore.org\n     &%ddiscord.gg/ssaREjBJXg     \n"
  value: "%afk%&%7%ping%ms"
  update-interval-ticks: 20

belowname:
  title: "&%c❤"
  value: "%afk%%health%"
  update-interval-ticks: 20

chat:
  enabled: true
  format: "{placeholder}{sender}&%7: &%f{message}"
  placeholder: ""
  click-to-message: true
  color-codes:
    enabled: true
    permission: "stellaria.chat.color"
  tooltip:
    enabled: true
    lines:
      - "&%7Ping: &%f%ping%ms"
      - "&%7所持金: &%e%money%"

tpa:
  teleport-delay-seconds: 5 # 承認後、実際にテレポートするまでの詠唱時間。0以下で即時テレポート。ダメージを受けるとキャンセルされる

teleport-effect:
  enabled: true
  particle: "DUST" # Bukkitの Particle enum名。DUSTの時だけ color/size が使われる
  color: "#55FFFF"
  size: 1.0
  radius: 1.0
  points: 30

mention:
  enabled: true
  format: "&%e@{name}&r"
  all:
    enabled: true
    keyword: "all"
    permission: "stellaria.chat.mention.all"
  sound:
    enabled: true
    name: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0
    pitch: 1.0

afk:
  enabled: true
  timeout-seconds: 300
  tag: "&%7[AFK] &r"
  actionbar-flash-seconds: 3

broadcast:
  auto:
    enabled: false
    interval-minutes: 5
    messages: []

mute:
  level3-command-blacklist:
    - "msg"
    - "tell"
    - "w"
    - "message"
    - "reply"
    - "r"
    - "mute"
    - "unmute"

message:
  color-codes:
    enabled: true
    permission: "stellaria.chat.color"
  sound:
    enabled: true
    name: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0
    pitch: 1.0

action-bar:
  enabled: true
  update-interval-ticks: 5
  separator: "&%7 | &r"
  persistent:
    enabled: false
    template: ""
