main: org.craftcore.stellaria.StellariaCore
version: ${version}
name: StellariaCore
author: Nyaffle, shu4700
description: Feature plugin for Stellaria MC
api-version: 1.21

depend: [Citizens, packetevents, Vault, PlaceholderAPI]
softdepend: [LuckPerms]

commands:
  tpa:
  tpaccept:
  tpdeny:
  tphere:
  tphaccept:
  tphdeny:
  stellariareload:
  afk:
  heal:
  broadcast:
    aliases: [bc]
  msg:
    aliases: [tell, w, message]
  reply:
    aliases: [r]
  mute:
  unmute:
  pay:
  eco:
  balance:
    aliases: [money, bal]
  colors:
  discord:
    aliases: [dc]
  playtime:
  seen:
  ranking:
    aliases: [rank]
  scoreboard:
    aliases: [sb]
  sethome:
  home:
  delhome:
  homes:
  setwarp:
  warp:
  delwarp:
  warps:
  weathervote:
  wvaccept:
  wvdeny:
  timevote:
  tvaccept:
  tvdeny:
  kikori:
  land:

permissions:
  stellaria.msg:
    default: true
  stellaria.pay:
    default: true
  stellaria.balance:
    default: true
  stellaria.playtime:
    default: true
  stellaria.seen:
    default: true
  stellaria.ranking:
    default: true
  stellaria.scoreboard:
    default: true
  stellaria.home:
    default: true
  stellaria.warp:
    default: true
  stellaria.land:
    default: true
  stellaria.land.admin:
    default: op
