main: org.craftcore.stellaria.StellariaCore
version: ${version}
name: StellariaCore
author: Nyaffle, shu4700
description: Feature plugin for Stellaria MC
api-version: 1.21

depend: [Citizens, packetevents, Vault, PlaceholderAPI]

commands:
  tpa:
  tpaccept:
  tpdeny:
  tphere:
  tphaccept:
  tphdeny:
  stellariareload:
  afk:
  heal:
  broadcast:
    aliases: [bc]
  msg:
    aliases: [tell, w, message]
  reply:
    aliases: [r]
  mute:
  unmute:

permissions:
  stellaria.msg:
    default: true
